# Generated by Django 4.0.2 on 2022-02-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='description',
            field=models.TextField(default='Arrangøren har ikke lagt ved noen beskrivelse'),
        ),
        migrations.AddField(
            model_name='hike',
            name='meetup',
            field=models.CharField(default='Arrangøren har ikke valgt et oppmøtested', max_length=50),
        ),
        migrations.AddField(
            model_name='hike',
            name='scheduled',
            field=models.DateTimeField(default='Ingen fastsatt tid'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
