# Generated by Django 4.0.2 on 2022-02-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_hike_description_hike_meetup_hike_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='picture',
        ),
    ]
