# Generated by Django 4.0.2 on 2022-02-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_hike_description_hike_meetup_hike_scheduled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hike',
            name='scheduled',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
