# Generated by Django 4.0.2 on 2022-03-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_hike_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hike',
            name='meetup',
            field=models.CharField(max_length=50),
        ),
    ]
